spring:
  application:
    name: Hospital Management Service
    
  profiles:
    active:
    - default
    
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:6551/hospital
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 3
      maximum-pool-size: 20
  read-datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:6551/hospital
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 3
      maximum-pool-size: 20

server:
  port: 3166
  
db-async-executor:
  pool-size:
    core: 10
    max: 100  